package main

import (
	"fmt"
	"os"

	"github.com/stellar/go-stellar-sdk/contract"
)

// emit writes a placeholder Go source file to outDir under packageName. It
// is the no-op stub described in T8.1; T8.2 will replace it with the real
// `text/template`-driven emitters for client.go, methods.go, types.go,
// errors.go, events.go, and spec.go.
//
// The placeholder records the number of decoded spec entries so the
// scaffolding is observable end-to-end (extract → emit) without coupling
// tests to the eventual template output.
func emit(outDir, packageName string, spec *contract.Spec) error {
	if spec == nil {
		return fmt.Errorf("nil spec")
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("creating output dir: %w", err)
	}
	body := fmt.Sprintf(`// Code generated by sorobangen. DO NOT EDIT.
//
// Placeholder produced by the T8.1 scaffolding. Real bindings will be
// emitted here once T8.2 lands the text/template pipeline.

package %s

// SpecEntryCount is the number of XDR ScSpecEntry records decoded from the
// source spec at generation time. It exists only so the placeholder file
// references the parsed input; T8.2 will remove it.
const SpecEntryCount = %d
`, packageName, len(spec.Entries()))

	path := outputFilePath(outDir, packageName)
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}
