package main

import (
	"encoding/base64"
	"fmt"
	"go/format"
	"os"
	"strings"

	"github.com/stellar/go-stellar-sdk/contract"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// emit writes a single Go source file under outDir that bundles every entry
// in spec into typed Go declarations: a Client wrapper, UDT type declarations,
// per-function method wrappers, and a package-level Spec() accessor backed by
// an embedded base64 dump of the source spec.
//
// The output passes through go/format.Source, so the on-disk text is
// gofmt-clean. If formatting fails (which would imply a bug in this emitter),
// the unformatted source is still written so the failure is debuggable.
//
// T8.3 will populate the init() body with contract.RegisterSpec /
// events.RegisterDecoder calls; this emitter leaves a TODO comment as a hook.
func emit(outDir, packageName string, spec *contract.Spec) error {
	if spec == nil {
		return fmt.Errorf("nil spec")
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("creating output dir: %w", err)
	}

	src, err := renderPackage(packageName, spec)
	if err != nil {
		return err
	}

	path := outputFilePath(outDir, packageName)
	if err := os.WriteFile(path, src, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// renderPackage assembles the generated source as raw bytes and runs them
// through go/format.Source. The packageName is trusted; the CLI's flag
// validation rejects empty values upstream.
func renderPackage(packageName string, spec *contract.Spec) ([]byte, error) {
	imps := newImportSet()

	// Render each entry first so we know which imports are needed.
	var typesBlock strings.Builder
	var funcsBlock strings.Builder
	for _, e := range spec.Entries() {
		switch e.Kind {
		case xdr.ScSpecEntryKindScSpecEntryUdtStructV0:
			if e.UdtStructV0 == nil {
				continue
			}
			typesBlock.WriteString(emitStruct(*e.UdtStructV0, imps))
			typesBlock.WriteString("\n")
		case xdr.ScSpecEntryKindScSpecEntryUdtEnumV0:
			if e.UdtEnumV0 == nil {
				continue
			}
			typesBlock.WriteString(emitEnum(*e.UdtEnumV0))
			typesBlock.WriteString("\n")
		case xdr.ScSpecEntryKindScSpecEntryUdtErrorEnumV0:
			if e.UdtErrorEnumV0 == nil {
				continue
			}
			imps.add("fmt")
			typesBlock.WriteString(emitErrorEnum(*e.UdtErrorEnumV0))
			typesBlock.WriteString("\n")
		case xdr.ScSpecEntryKindScSpecEntryUdtUnionV0:
			if e.UdtUnionV0 == nil {
				continue
			}
			typesBlock.WriteString(emitUnion(*e.UdtUnionV0, imps))
			typesBlock.WriteString("\n")
		case xdr.ScSpecEntryKindScSpecEntryFunctionV0:
			if e.FunctionV0 == nil {
				continue
			}
			funcsBlock.WriteString(emitFunc(*e.FunctionV0, imps))
			funcsBlock.WriteString("\n")
		}
	}

	// Spec accessor + Client wrapper need these unconditionally so the
	// generated package compiles even when the spec has no entries.
	imps.add("github.com/stellar/go-stellar-sdk/contract")

	specB64, err := encodeSpec(spec)
	if err != nil {
		return nil, fmt.Errorf("encoding spec: %w", err)
	}

	var b strings.Builder
	b.WriteString("// Code generated by sorobangen. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Source: Soroban contract spec entries decoded at generation time.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)

	if len(imps) > 0 {
		b.WriteString("import (\n")
		for _, p := range imps.sortedPaths() {
			fmt.Fprintf(&b, "\t%q\n", p)
		}
		b.WriteString(")\n\n")
	}

	// Spec accessor: a package-level *contract.Spec, lazily decoded at
	// package init so callers don't pay the decode on every Spec() call.
	fmt.Fprintf(&b, "// specBase64 is the base64-encoded XDR stream of ScSpecEntry records this\n")
	b.WriteString("// package was generated from. It is decoded once at init.\n")
	fmt.Fprintf(&b, "const specBase64 = %q\n\n", specB64)

	b.WriteString("// pkgSpec holds the parsed contract Spec. Use Spec() to access it.\n")
	b.WriteString("var pkgSpec *contract.Spec\n\n")

	b.WriteString("// Spec returns the contract spec bundled with this generated package.\n")
	b.WriteString("// It is safe to share across goroutines.\n")
	b.WriteString("func Spec() *contract.Spec { return pkgSpec }\n\n")

	b.WriteString("func init() {\n")
	b.WriteString("\ts, err := contract.NewSpecFromBase64(specBase64)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\t// The spec is embedded at generation time, so a decode failure\n")
	b.WriteString("\t\t// here means the binding was emitted from corrupt input. Panic so\n")
	b.WriteString("\t\t// the broken package fails loudly at import.\n")
	b.WriteString("\t\tpanic(\"sorobangen: failed to decode embedded spec: \" + err.Error())\n")
	b.WriteString("\t}\n")
	b.WriteString("\tpkgSpec = s\n")
	b.WriteString("\t// TODO(T8.3): wire registry registration here:\n")
	b.WriteString("\t//   contract.RegisterSpec(contractID, s)\n")
	b.WriteString("\t//   events.RegisterDecoder(contractID, eventName, decoder)\n")
	b.WriteString("\t// The generated package does not know its deployed contractID; T8.3\n")
	b.WriteString("\t// will surface a generation-time flag (`--contract-id`) and emit the\n")
	b.WriteString("\t// call site here.\n")
	b.WriteString("}\n\n")

	// Client wrapper. The struct embeds *contract.Client behind an unexported
	// field so methods can call c.inner.Invoke without exposing the raw
	// client surface as part of the generated API. Callers who need the
	// underlying client get it via Inner().
	b.WriteString("// Client is the typed entry point for invoking this contract's functions.\n")
	b.WriteString("// It wraps a *contract.Client and forwards each method to Invoke with the\n")
	b.WriteString("// bundled Spec already bound.\n")
	b.WriteString("type Client struct {\n")
	b.WriteString("\tinner *contract.Client\n")
	b.WriteString("}\n\n")

	b.WriteString("// NewClient constructs a typed Client over a *contract.Client. The supplied\n")
	b.WriteString("// inner client should target this package's contract; the bundled Spec is\n")
	b.WriteString("// applied via WithSpec when missing so generated methods can marshal args.\n")
	b.WriteString("func NewClient(inner *contract.Client) *Client {\n")
	b.WriteString("\treturn &Client{inner: inner}\n")
	b.WriteString("}\n\n")

	b.WriteString("// Inner returns the underlying *contract.Client. Useful for callers that\n")
	b.WriteString("// need the generic Invoke / InvokeAndConfirm surface.\n")
	b.WriteString("func (c *Client) Inner() *contract.Client { return c.inner }\n\n")

	// Types + functions blocks.
	if typesBlock.Len() > 0 {
		b.WriteString(typesBlock.String())
	}
	if funcsBlock.Len() > 0 {
		b.WriteString(funcsBlock.String())
	}

	raw := []byte(b.String())
	formatted, err := format.Source(raw)
	if err != nil {
		// Don't lose the source — return it so callers can inspect.
		return raw, fmt.Errorf("formatting generated source: %w", err)
	}
	return formatted, nil
}

// encodeSpec serializes a *contract.Spec back into the same base64 XDR stream
// contract.NewSpecFromBase64 reads. Round-trip is required because Spec only
// exposes its decoded entries, not the raw bytes it was built from.
func encodeSpec(spec *contract.Spec) (string, error) {
	entries := spec.Entries()
	var buf []byte
	for i := range entries {
		raw, err := entries[i].MarshalBinary()
		if err != nil {
			return "", fmt.Errorf("marshal entry %d: %w", i, err)
		}
		buf = append(buf, raw...)
	}
	return base64.StdEncoding.EncodeToString(buf), nil
}
