package main

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stellar/go-stellar-sdk/xdr"
)

func TestRun_FromWasm_WritesPlaceholder(t *testing.T) {
	wasm := buildWasm(t, "contractspecv0", encodeEntries(t, []xdr.ScSpecEntry{fnEntry(t, "transfer")}))
	dir := t.TempDir()
	wasmPath := filepath.Join(dir, "c.wasm")
	if err := os.WriteFile(wasmPath, wasm, 0o644); err != nil {
		t.Fatalf("seed wasm: %v", err)
	}
	outDir := filepath.Join(dir, "out")

	if err := run([]string{"-wasm", wasmPath, "-out", outDir, "-package", "token"}, io.Discard); err != nil {
		t.Fatalf("run: %v", err)
	}

	got, err := os.ReadFile(outputFilePath(outDir, "token"))
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	body := string(got)
	if !strings.Contains(body, "Code generated by sorobangen") {
		t.Errorf("missing generated header in %q", body)
	}
	if !strings.Contains(body, "package token") {
		t.Errorf("missing package decl in %q", body)
	}
	if !strings.Contains(body, "SpecEntryCount = 1") {
		t.Errorf("expected entry count 1, got %q", body)
	}
}

func TestRun_FromSpec_WritesPlaceholder(t *testing.T) {
	raw := encodeEntries(t, []xdr.ScSpecEntry{fnEntry(t, "balance"), fnEntry(t, "transfer")})
	dir := t.TempDir()
	specPath := filepath.Join(dir, "spec.bin")
	if err := os.WriteFile(specPath, raw, 0o644); err != nil {
		t.Fatalf("seed spec: %v", err)
	}
	outDir := filepath.Join(dir, "out")

	if err := run([]string{"-spec", specPath, "-out", outDir, "-package", "tok"}, io.Discard); err != nil {
		t.Fatalf("run: %v", err)
	}

	got, err := os.ReadFile(outputFilePath(outDir, "tok"))
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	if !strings.Contains(string(got), "SpecEntryCount = 2") {
		t.Errorf("expected entry count 2, got %q", string(got))
	}
}

func TestRun_MissingCustomSection(t *testing.T) {
	wasm := buildWasm(t, "other", []byte{0x01})
	dir := t.TempDir()
	wasmPath := filepath.Join(dir, "c.wasm")
	if err := os.WriteFile(wasmPath, wasm, 0o644); err != nil {
		t.Fatalf("seed wasm: %v", err)
	}

	err := run([]string{"-wasm", wasmPath, "-out", filepath.Join(dir, "out"), "-package", "token"}, io.Discard)
	if err == nil {
		t.Fatal("expected error for missing contractspecv0 section")
	}
	if !strings.Contains(err.Error(), "contractspecv0") {
		t.Errorf("error %q does not mention contractspecv0", err)
	}
}

func TestRun_GarbageWasm(t *testing.T) {
	dir := t.TempDir()
	wasmPath := filepath.Join(dir, "c.wasm")
	if err := os.WriteFile(wasmPath, []byte("not a wasm module"), 0o644); err != nil {
		t.Fatalf("seed wasm: %v", err)
	}

	err := run([]string{"-wasm", wasmPath, "-out", filepath.Join(dir, "out"), "-package", "token"}, io.Discard)
	if err == nil {
		t.Fatal("expected error for invalid wasm")
	}
}

func TestRun_FlagValidation(t *testing.T) {
	dir := t.TempDir()
	cases := []struct {
		name    string
		args    []string
		wantSub string
	}{
		{
			name:    "no input",
			args:    []string{"-out", dir, "-package", "p"},
			wantSub: "-wasm or -spec",
		},
		{
			name:    "both inputs",
			args:    []string{"-wasm", "a", "-spec", "b", "-out", dir, "-package", "p"},
			wantSub: "mutually exclusive",
		},
		{
			name:    "missing out",
			args:    []string{"-wasm", "a", "-package", "p"},
			wantSub: "-out",
		},
		{
			name:    "missing package",
			args:    []string{"-wasm", "a", "-out", dir},
			wantSub: "-package",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := run(tc.args, io.Discard)
			if err == nil {
				t.Fatal("expected error")
			}
			if !strings.Contains(err.Error(), tc.wantSub) {
				t.Errorf("error %q missing %q", err, tc.wantSub)
			}
		})
	}
}

// --- helpers (local to this test file so the CLI has no test-only exports) ---

func fnEntry(t *testing.T, name string) xdr.ScSpecEntry {
	t.Helper()
	fn := xdr.ScSpecFunctionV0{
		Name:    xdr.ScSymbol(name),
		Inputs:  nil,
		Outputs: nil,
	}
	e, err := xdr.NewScSpecEntry(xdr.ScSpecEntryKindScSpecEntryFunctionV0, fn)
	if err != nil {
		t.Fatalf("build entry: %v", err)
	}
	return e
}

func encodeEntries(t *testing.T, entries []xdr.ScSpecEntry) []byte {
	t.Helper()
	var buf bytes.Buffer
	for i := range entries {
		if _, err := xdr.Marshal(&buf, &entries[i]); err != nil {
			t.Fatalf("marshal entry: %v", err)
		}
	}
	return buf.Bytes()
}

// buildWasm produces the minimum well-formed WebAssembly module that
// contains a single custom section. Mirrors the helper used by the
// contract package's spec_test.go.
func buildWasm(t *testing.T, name string, payload []byte) []byte {
	t.Helper()
	var w bytes.Buffer
	w.Write([]byte{0x00, 'a', 's', 'm', 0x01, 0x00, 0x00, 0x00})

	var body bytes.Buffer
	writeVarUint32(&body, uint32(len(name)))
	body.WriteString(name)
	body.Write(payload)

	w.WriteByte(0x00) // custom section id
	writeVarUint32(&w, uint32(body.Len()))
	w.Write(body.Bytes())
	return w.Bytes()
}

func writeVarUint32(w *bytes.Buffer, v uint32) {
	for {
		b := byte(v & 0x7f)
		v >>= 7
		if v != 0 {
			b |= 0x80
		}
		w.WriteByte(b)
		if v == 0 {
			return
		}
	}
}
